Import Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Imorting the Dataset

In [3]:
dataset = pd.read_csv('Data.csv')

# Features
# [Row , column]
X = dataset.iloc[:, :-1].values

# Dependent variable vector
# the values convert to numpy array
y = dataset.iloc[:,-1].values


print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing data

In [4]:
# Replacing the missing data with average of that column

# We use scikit learn all this course , here also it uses

from sklearn.impute import SimpleImputer

#Simple Imputer
imputer = SimpleImputer(missing_values =np.nan ,strategy='mean')
imputer.fit(X[:,1:3])
# transform gives new updated list seperately
X[:,1:3] = imputer.transform(X[:,1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding categorical data

In [5]:
# Converting String into numbers
# One hot encoding is used (most famous)

# Column transform from scikit learn
from sklearn.compose import ColumnTransformer

# One hot encoding class
from sklearn.preprocessing import OneHotEncoder

#object
# transformer => what we need to do - endcode
# What type of encoding - onehot encoding
# Which column - [0]
# remainder => if we wont use , that only encode 3 columns only
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[0])],remainder='passthrough')

X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding Dependent variable

In [6]:
# COnverting yes, no to 0s and 1s

from sklearn.preprocessing import LabelEncoder
#object
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1]


Split Training set and Test set

In [7]:
# This splitting must before the feature scaling

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

# The random state used to map the same x train, y train and x test y test
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


Feature Scaling

In [10]:
# Always the feature scaling must be  after splitting train and test set

# Because feature scaling takes means ans other stuff in the data
# If we use feature scaling before , it some info leakage of the test set also
# So it  is not a good  way , so use after splitting


# Here we  use sttandardization -3 to 3
# there is no necessary to apply sc for dummy values (Contries)  because it already in that  range


from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:] )
X_test[:, 3:] = sc.transform(X_test[:, 3:] )

# on test data , only transform is used , because it used the fit data from the  train data , we want that (google it why)

print(X_train)
print()
print(X_test)

[[0.0 0.0 1.0 -0.1915918438457856 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057902 -0.07013167641635401]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022488 -0.30786617274297895]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]

[[0.0 1.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [1.0 0.0 0.0 -0.44973664397484425 0.20564033932253029]]
